import type { ReportMetadata } from "../../../types";
import { formatDate } from "./formatUtils";

interface FooterProps {
  metadata: ReportMetadata;
}

export function Footer({ metadata }: FooterProps) {
  const generatedDate = formatDate(metadata.generatedAt);
  const startDate = formatDate(metadata.dateRange.start);
  const endDate = formatDate(metadata.dateRange.end);

  return (
    <footer class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 mt-8 border-t border-gray-200 dark:border-gray-700">
      <div class="space-y-3 text-sm text-gray-600 dark:text-gray-400">
        <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
          <div>
            Builds: {metadata.buildCount} · {startDate} – {endDate}
          </div>
        </div>
        <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
          <div>
            Generated by <span class="font-semibold">Unentropy</span> v0.1.0 on {generatedDate}
          </div>
          <div class="mt-2 sm:mt-0">
            <a
              href="https://unentropy.dev/getting-started/"
              class="hover:text-gray-900 dark:hover:text-white"
            >
              View Documentation
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}
