name: "Unentropy Quality Gate"
description: "Evaluate PR metrics against baseline thresholds and post results"
author: "Unentropy"
branding:
  icon: "shield"
  color: "green"

inputs:
  storage-type:
    description: "Storage backend type (sqlite-local, sqlite-s3, sqlite-artifact)"
    required: false
    default: "sqlite-artifact"

  s3-endpoint:
    description: "S3-compatible endpoint URL"
    required: false

  s3-bucket:
    description: "S3 bucket name"
    required: false

  s3-region:
    description: "S3 region"
    required: false

  s3-access-key-id:
    description: "S3 access key ID (from GitHub Secrets)"
    required: false

  s3-secret-access-key:
    description: "S3 secret access key (from GitHub Secrets)"
    required: false

  database-key:
    description: "Database file key in storage"
    required: false
    default: "unentropy.db"

  config-file:
    description: "Path to unentropy.json configuration file"
    required: false
    default: "unentropy.json"

  quality-gate-mode:
    description: "Gate mode: off, soft, or hard (overrides config file)"
    required: false

  enable-pr-comment:
    description: "Post/update PR comment with gate results"
    required: false
    default: "true"

  pr-comment-marker:
    description: "HTML marker to identify canonical gate comment"
    required: false
    default: "<!-- unentropy-quality-gate -->"

  max-pr-comment-metrics:
    description: "Maximum metrics to show in PR comment"
    required: false
    default: "30"

outputs:
  quality-gate-status:
    description: "Overall gate status: pass, fail, or unknown"
    value: ${{ steps.gate.outputs.quality-gate-status }}

  quality-gate-mode:
    description: "Gate mode used: off, soft, or hard"
    value: ${{ steps.gate.outputs.quality-gate-mode }}

  quality-gate-failing-metrics:
    description: "Comma-separated list of failing metric names"
    value: ${{ steps.gate.outputs.quality-gate-failing-metrics }}

  quality-gate-comment-url:
    description: "URL of the PR comment (if created)"
    value: ${{ steps.gate.outputs.quality-gate-comment-url }}

  metrics-collected:
    description: "Number of metrics collected from PR"
    value: ${{ steps.gate.outputs.metrics-collected }}

  baseline-builds-considered:
    description: "Number of baseline builds used for comparison"
    value: ${{ steps.gate.outputs.baseline-builds-considered }}

  baseline-reference-branch:
    description: "Reference branch used for baseline"
    value: ${{ steps.gate.outputs.baseline-reference-branch }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.3.3"

    - name: Install scc (Code Counter)
      shell: bash
      run: |
        wget -qO scc.tar.gz https://github.com/boyter/scc/releases/latest/download/scc_Linux_x86_64.tar.gz
        sudo tar xf scc.tar.gz -C /usr/local/bin scc
        scc --version

    - name: Run quality gate evaluation
      id: gate
      shell: bash
      run: |
        bun "${{ github.action_path }}/dist/quality-gate.js"
      env:
        INPUT_STORAGE-TYPE: ${{ inputs.storage-type }}
        INPUT_S3-ENDPOINT: ${{ inputs.s3-endpoint }}
        INPUT_S3-BUCKET: ${{ inputs.s3-bucket }}
        INPUT_S3-REGION: ${{ inputs.s3-region }}
        INPUT_S3-ACCESS-KEY-ID: ${{ inputs.s3-access-key-id }}
        INPUT_S3-SECRET-ACCESS-KEY: ${{ inputs.s3-secret-access-key }}
        INPUT_DATABASE-KEY: ${{ inputs.database-key }}
        INPUT_CONFIG-FILE: ${{ inputs.config-file }}
        INPUT_QUALITY-GATE-MODE: ${{ inputs.quality-gate-mode }}
        INPUT_ENABLE-PR-COMMENT: ${{ inputs.enable-pr-comment }}
        INPUT_PR-COMMENT-MARKER: ${{ inputs.pr-comment-marker }}
        INPUT_MAX-PR-COMMENT-METRICS: ${{ inputs.max-pr-comment-metrics }}
        GITHUB_TOKEN: ${{ github.token }}
